name: Bash script-execution

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Execution rights
        run: chmod +x ./script.sh
        
      - name: Script execution
        run: ./script.sh
